/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package alljoyn;

public class _AJ_Message {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected _AJ_Message(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_AJ_Message obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        alljoynJNI.delete__AJ_Message(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMsgId(long value) {
    alljoynJNI._AJ_Message_msgId_set(swigCPtr, this, value);
  }

  public long getMsgId() {
    return alljoynJNI._AJ_Message_msgId_get(swigCPtr, this);
  }

  public void setHdr(AJ_MsgHeader value) {
    alljoynJNI._AJ_Message_hdr_set(swigCPtr, this, AJ_MsgHeader.getCPtr(value), value);
  }

  public AJ_MsgHeader getHdr() {
    long cPtr = alljoynJNI._AJ_Message_hdr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new AJ_MsgHeader(cPtr, false);
  }

  public void setObjPath(String value) {
    alljoynJNI._AJ_Message_objPath_set(swigCPtr, this, value);
  }

  public String getObjPath() {
    return alljoynJNI._AJ_Message_objPath_get(swigCPtr, this);
  }

  public void setReplySerial(long value) {
    alljoynJNI._AJ_Message_replySerial_set(swigCPtr, this, value);
  }

  public long getReplySerial() {
    return alljoynJNI._AJ_Message_replySerial_get(swigCPtr, this);
  }

  public void setMember(String value) {
    alljoynJNI._AJ_Message_member_set(swigCPtr, this, value);
  }

  public String getMember() {
    return alljoynJNI._AJ_Message_member_get(swigCPtr, this);
  }

  public void setError(String value) {
    alljoynJNI._AJ_Message_error_set(swigCPtr, this, value);
  }

  public String getError() {
    return alljoynJNI._AJ_Message_error_get(swigCPtr, this);
  }

  public void setIface(String value) {
    alljoynJNI._AJ_Message_iface_set(swigCPtr, this, value);
  }

  public String getIface() {
    return alljoynJNI._AJ_Message_iface_get(swigCPtr, this);
  }

  public void setSender(String value) {
    alljoynJNI._AJ_Message_sender_set(swigCPtr, this, value);
  }

  public String getSender() {
    return alljoynJNI._AJ_Message_sender_get(swigCPtr, this);
  }

  public void setDestination(String value) {
    alljoynJNI._AJ_Message_destination_set(swigCPtr, this, value);
  }

  public String getDestination() {
    return alljoynJNI._AJ_Message_destination_get(swigCPtr, this);
  }

  public void setSignature(String value) {
    alljoynJNI._AJ_Message_signature_set(swigCPtr, this, value);
  }

  public String getSignature() {
    return alljoynJNI._AJ_Message_signature_get(swigCPtr, this);
  }

  public void setSessionId(long value) {
    alljoynJNI._AJ_Message_sessionId_set(swigCPtr, this, value);
  }

  public long getSessionId() {
    return alljoynJNI._AJ_Message_sessionId_get(swigCPtr, this);
  }

  public void setTimestamp(long value) {
    alljoynJNI._AJ_Message_timestamp_set(swigCPtr, this, value);
  }

  public long getTimestamp() {
    return alljoynJNI._AJ_Message_timestamp_get(swigCPtr, this);
  }

  public void setTtl(long value) {
    alljoynJNI._AJ_Message_ttl_set(swigCPtr, this, value);
  }

  public long getTtl() {
    return alljoynJNI._AJ_Message_ttl_get(swigCPtr, this);
  }

  public void setSigOffset(int value) {
    alljoynJNI._AJ_Message_sigOffset_set(swigCPtr, this, value);
  }

  public int getSigOffset() {
    return alljoynJNI._AJ_Message_sigOffset_get(swigCPtr, this);
  }

  public void setVarOffset(int value) {
    alljoynJNI._AJ_Message_varOffset_set(swigCPtr, this, value);
  }

  public int getVarOffset() {
    return alljoynJNI._AJ_Message_varOffset_get(swigCPtr, this);
  }

  public void setBodyBytes(long value) {
    alljoynJNI._AJ_Message_bodyBytes_set(swigCPtr, this, value);
  }

  public long getBodyBytes() {
    return alljoynJNI._AJ_Message_bodyBytes_get(swigCPtr, this);
  }

  public void setBus(AJ_BusAttachment value) {
    alljoynJNI._AJ_Message_bus_set(swigCPtr, this, AJ_BusAttachment.getCPtr(value), value);
  }

  public AJ_BusAttachment getBus() {
    long cPtr = alljoynJNI._AJ_Message_bus_get(swigCPtr, this);
    return (cPtr == 0) ? null : new AJ_BusAttachment(cPtr, false);
  }

  public void setOuter(_AJ_Arg value) {
    alljoynJNI._AJ_Message_outer_set(swigCPtr, this, _AJ_Arg.getCPtr(value), value);
  }

  public _AJ_Arg getOuter() {
    long cPtr = alljoynJNI._AJ_Message_outer_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _AJ_Arg(cPtr, false);
  }

  public _AJ_Message() {
    this(alljoynJNI.new__AJ_Message(), true);
  }

}
