/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package alljoyn;

public class _AJ_Arg {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected _AJ_Arg(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_AJ_Arg obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        alljoynJNI.delete__AJ_Arg(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTypeId(int value) {
    alljoynJNI._AJ_Arg_typeId_set(swigCPtr, this, value);
  }

  public int getTypeId() {
    return alljoynJNI._AJ_Arg_typeId_get(swigCPtr, this);
  }

  public void setFlags(int value) {
    alljoynJNI._AJ_Arg_flags_set(swigCPtr, this, value);
  }

  public int getFlags() {
    return alljoynJNI._AJ_Arg_flags_get(swigCPtr, this);
  }

  public void setLen(long value) {
    alljoynJNI._AJ_Arg_len_set(swigCPtr, this, value);
  }

  public long getLen() {
    return alljoynJNI._AJ_Arg_len_get(swigCPtr, this);
  }

  public _AJ_Arg_val getVal() {
    long cPtr = alljoynJNI._AJ_Arg_val_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _AJ_Arg_val(cPtr, false);
  }

  public void setSigPtr(String value) {
    alljoynJNI._AJ_Arg_sigPtr_set(swigCPtr, this, value);
  }

  public String getSigPtr() {
    return alljoynJNI._AJ_Arg_sigPtr_get(swigCPtr, this);
  }

  public void setContainer(_AJ_Arg value) {
    alljoynJNI._AJ_Arg_container_set(swigCPtr, this, _AJ_Arg.getCPtr(value), value);
  }

  public _AJ_Arg getContainer() {
    long cPtr = alljoynJNI._AJ_Arg_container_get(swigCPtr, this);
    return (cPtr == 0) ? null : new _AJ_Arg(cPtr, false);
  }

  public _AJ_Arg() {
    this(alljoynJNI.new__AJ_Arg(), true);
  }

}
