/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package alljoyn;

public class AJ_Credential {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected AJ_Credential(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AJ_Credential obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        alljoynJNI.delete_AJ_Credential(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMask(long value) {
    alljoynJNI.AJ_Credential_mask_set(swigCPtr, this, value);
  }

  public long getMask() {
    return alljoynJNI.AJ_Credential_mask_get(swigCPtr, this);
  }

  public void setExpiration(long value) {
    alljoynJNI.AJ_Credential_expiration_set(swigCPtr, this, value);
  }

  public long getExpiration() {
    return alljoynJNI.AJ_Credential_expiration_get(swigCPtr, this);
  }

  public void setData(SWIGTYPE_p_uint8_t value) {
    alljoynJNI.AJ_Credential_data_set(swigCPtr, this, SWIGTYPE_p_uint8_t.getCPtr(value));
  }

  public SWIGTYPE_p_uint8_t getData() {
    long cPtr = alljoynJNI.AJ_Credential_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_uint8_t(cPtr, false);
  }

  public void setLen(long value) {
    alljoynJNI.AJ_Credential_len_set(swigCPtr, this, value);
  }

  public long getLen() {
    return alljoynJNI.AJ_Credential_len_get(swigCPtr, this);
  }

  public AJ_Credential() {
    this(alljoynJNI.new_AJ_Credential(), true);
  }

}
