/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package alljoyn;

public final class AJ_MemberType {
  public final static AJ_MemberType AJ_INVALID_MEMBER = new AJ_MemberType("AJ_INVALID_MEMBER", alljoynJNI.AJ_INVALID_MEMBER_get());
  public final static AJ_MemberType AJ_SIGNAL_MEMBER = new AJ_MemberType("AJ_SIGNAL_MEMBER", alljoynJNI.AJ_SIGNAL_MEMBER_get());
  public final static AJ_MemberType AJ_METHOD_MEMBER = new AJ_MemberType("AJ_METHOD_MEMBER", alljoynJNI.AJ_METHOD_MEMBER_get());
  public final static AJ_MemberType AJ_PROPERTY_MEMBER = new AJ_MemberType("AJ_PROPERTY_MEMBER", alljoynJNI.AJ_PROPERTY_MEMBER_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static AJ_MemberType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + AJ_MemberType.class + " with value " + swigValue);
  }

  private AJ_MemberType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private AJ_MemberType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private AJ_MemberType(String swigName, AJ_MemberType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static AJ_MemberType[] swigValues = { AJ_INVALID_MEMBER, AJ_SIGNAL_MEMBER, AJ_METHOD_MEMBER, AJ_PROPERTY_MEMBER };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

