/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package alljoyn;

public class AJ_MsgHeader {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected AJ_MsgHeader(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AJ_MsgHeader obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        alljoynJNI.delete_AJ_MsgHeader(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setEndianess(char value) {
    alljoynJNI.AJ_MsgHeader_endianess_set(swigCPtr, this, value);
  }

  public char getEndianess() {
    return alljoynJNI.AJ_MsgHeader_endianess_get(swigCPtr, this);
  }

  public void setMsgType(int value) {
    alljoynJNI.AJ_MsgHeader_msgType_set(swigCPtr, this, value);
  }

  public int getMsgType() {
    return alljoynJNI.AJ_MsgHeader_msgType_get(swigCPtr, this);
  }

  public void setFlags(int value) {
    alljoynJNI.AJ_MsgHeader_flags_set(swigCPtr, this, value);
  }

  public int getFlags() {
    return alljoynJNI.AJ_MsgHeader_flags_get(swigCPtr, this);
  }

  public void setMajorVersion(int value) {
    alljoynJNI.AJ_MsgHeader_majorVersion_set(swigCPtr, this, value);
  }

  public int getMajorVersion() {
    return alljoynJNI.AJ_MsgHeader_majorVersion_get(swigCPtr, this);
  }

  public void setBodyLen(long value) {
    alljoynJNI.AJ_MsgHeader_bodyLen_set(swigCPtr, this, value);
  }

  public long getBodyLen() {
    return alljoynJNI.AJ_MsgHeader_bodyLen_get(swigCPtr, this);
  }

  public void setSerialNum(long value) {
    alljoynJNI.AJ_MsgHeader_serialNum_set(swigCPtr, this, value);
  }

  public long getSerialNum() {
    return alljoynJNI.AJ_MsgHeader_serialNum_get(swigCPtr, this);
  }

  public void setHeaderLen(long value) {
    alljoynJNI.AJ_MsgHeader_headerLen_set(swigCPtr, this, value);
  }

  public long getHeaderLen() {
    return alljoynJNI.AJ_MsgHeader_headerLen_get(swigCPtr, this);
  }

  public AJ_MsgHeader() {
    this(alljoynJNI.new_AJ_MsgHeader(), true);
  }

}
