/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package alljoyn;

public class AJ_ObjectIterator {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected AJ_ObjectIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AJ_ObjectIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        alljoynJNI.delete_AJ_ObjectIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFin(int value) {
    alljoynJNI.AJ_ObjectIterator_fin_set(swigCPtr, this, value);
  }

  public int getFin() {
    return alljoynJNI.AJ_ObjectIterator_fin_get(swigCPtr, this);
  }

  public void setFex(int value) {
    alljoynJNI.AJ_ObjectIterator_fex_set(swigCPtr, this, value);
  }

  public int getFex() {
    return alljoynJNI.AJ_ObjectIterator_fex_get(swigCPtr, this);
  }

  public void setL(int value) {
    alljoynJNI.AJ_ObjectIterator_l_set(swigCPtr, this, value);
  }

  public int getL() {
    return alljoynJNI.AJ_ObjectIterator_l_get(swigCPtr, this);
  }

  public void setN(long value) {
    alljoynJNI.AJ_ObjectIterator_n_set(swigCPtr, this, value);
  }

  public long getN() {
    return alljoynJNI.AJ_ObjectIterator_n_get(swigCPtr, this);
  }

  public AJ_ObjectIterator() {
    this(alljoynJNI.new_AJ_ObjectIterator(), true);
  }

}
