/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package alljoyn;

public class AJ_Object {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected AJ_Object(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AJ_Object obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        alljoynJNI.delete_AJ_Object(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPath(String value) {
    alljoynJNI.AJ_Object_path_set(swigCPtr, this, value);
  }

  public String getPath() {
    return alljoynJNI.AJ_Object_path_get(swigCPtr, this);
  }

  public void setInterfaces(SWIGTYPE_p_p_p_char value) {
    alljoynJNI.AJ_Object_interfaces_set(swigCPtr, this, SWIGTYPE_p_p_p_char.getCPtr(value));
  }

  public SWIGTYPE_p_p_p_char getInterfaces() {
    long cPtr = alljoynJNI.AJ_Object_interfaces_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_p_char(cPtr, false);
  }

  public void setFlags(int value) {
    alljoynJNI.AJ_Object_flags_set(swigCPtr, this, value);
  }

  public int getFlags() {
    return alljoynJNI.AJ_Object_flags_get(swigCPtr, this);
  }

  public void setContext(SWIGTYPE_p_void value) {
    alljoynJNI.AJ_Object_context_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getContext() {
    long cPtr = alljoynJNI.AJ_Object_context_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public AJ_Object() {
    this(alljoynJNI.new_AJ_Object(), true);
  }

}
