/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package alljoyn;

public class AJ_SessionOpts {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected AJ_SessionOpts(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AJ_SessionOpts obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        alljoynJNI.delete_AJ_SessionOpts(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTraffic(int value) {
    alljoynJNI.AJ_SessionOpts_traffic_set(swigCPtr, this, value);
  }

  public int getTraffic() {
    return alljoynJNI.AJ_SessionOpts_traffic_get(swigCPtr, this);
  }

  public void setProximity(int value) {
    alljoynJNI.AJ_SessionOpts_proximity_set(swigCPtr, this, value);
  }

  public int getProximity() {
    return alljoynJNI.AJ_SessionOpts_proximity_get(swigCPtr, this);
  }

  public void setTransports(long value) {
    alljoynJNI.AJ_SessionOpts_transports_set(swigCPtr, this, value);
  }

  public long getTransports() {
    return alljoynJNI.AJ_SessionOpts_transports_get(swigCPtr, this);
  }

  public void setIsMultipoint(long value) {
    alljoynJNI.AJ_SessionOpts_isMultipoint_set(swigCPtr, this, value);
  }

  public long getIsMultipoint() {
    return alljoynJNI.AJ_SessionOpts_isMultipoint_get(swigCPtr, this);
  }

  public AJ_SessionOpts() {
    this(alljoynJNI.new_AJ_SessionOpts(), true);
  }

}
