/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package alljoyn;

public class AJ_Time {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected AJ_Time(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AJ_Time obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        alljoynJNI.delete_AJ_Time(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMilliseconds(long value) {
    alljoynJNI.AJ_Time_milliseconds_set(swigCPtr, this, value);
  }

  public long getMilliseconds() {
    return alljoynJNI.AJ_Time_milliseconds_get(swigCPtr, this);
  }

  public void setSeconds(long value) {
    alljoynJNI.AJ_Time_seconds_set(swigCPtr, this, value);
  }

  public long getSeconds() {
    return alljoynJNI.AJ_Time_seconds_get(swigCPtr, this);
  }

  public AJ_Time() {
    this(alljoynJNI.new_AJ_Time(), true);
  }

}
