/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package alljoyn;

public class alljoyn implements alljoynConstants {
  public static void setDbgINIT(int value) {
    alljoynJNI.dbgINIT_set(value);
  }

  public static int getDbgINIT() {
    return alljoynJNI.dbgINIT_get();
  }

  public static void setDbgNET(int value) {
    alljoynJNI.dbgNET_set(value);
  }

  public static int getDbgNET() {
    return alljoynJNI.dbgNET_get();
  }

  public static void setDbgTARGET_UTIL(int value) {
    alljoynJNI.dbgTARGET_UTIL_set(value);
  }

  public static int getDbgTARGET_UTIL() {
    return alljoynJNI.dbgTARGET_UTIL_get();
  }

  public static void AJ_IOBufInit(AJ_IOBuffer ioBuf, SWIGTYPE_p_uint8_t buffer, long bufLen, int direction, SWIGTYPE_p_void context) {
    alljoynJNI.AJ_IOBufInit(AJ_IOBuffer.getCPtr(ioBuf), ioBuf, SWIGTYPE_p_uint8_t.getCPtr(buffer), bufLen, direction, SWIGTYPE_p_void.getCPtr(context));
  }

  public static void AJ_IOBufRebase(AJ_IOBuffer ioBuf, long preserve) {
    alljoynJNI.AJ_IOBufRebase(AJ_IOBuffer.getCPtr(ioBuf), ioBuf, preserve);
  }

  public static AJ_Status AJ_Net_Connect(AJ_NetSocket netSock, long port, int addrType, SWIGTYPE_p_uint32_t addr) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_Net_Connect(AJ_NetSocket.getCPtr(netSock), netSock, port, addrType, SWIGTYPE_p_uint32_t.getCPtr(addr)));
  }

  public static void AJ_Net_Disconnect(AJ_NetSocket netSock) {
    alljoynJNI.AJ_Net_Disconnect(AJ_NetSocket.getCPtr(netSock), netSock);
  }

  public static AJ_Status AJ_Net_Send(AJ_IOBuffer txBuf) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_Net_Send(AJ_IOBuffer.getCPtr(txBuf), txBuf));
  }

  public static AJ_Status AJ_Net_Recv(AJ_IOBuffer rxBuf, long len, long timeout) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_Net_Recv(AJ_IOBuffer.getCPtr(rxBuf), rxBuf, len, timeout));
  }

  public static AJ_Status AJ_Net_MCastUp(AJ_MCastSocket mcastSock) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_Net_MCastUp(AJ_MCastSocket.getCPtr(mcastSock), mcastSock));
  }

  public static void AJ_Net_MCastDown(AJ_MCastSocket mcastSock) {
    alljoynJNI.AJ_Net_MCastDown(AJ_MCastSocket.getCPtr(mcastSock), mcastSock);
  }

  public static void AJ_Net_Interrupt() {
    alljoynJNI.AJ_Net_Interrupt();
  }

  public static String AJ_GetLine(String str, long num, SWIGTYPE_p_void fp) {
    return alljoynJNI.AJ_GetLine(str, num, SWIGTYPE_p_void.getCPtr(fp));
  }

  public static String AJ_GetCmdLine(String buf, long num) {
    return alljoynJNI.AJ_GetCmdLine(buf, num);
  }

  public static String AJ_GetVersion() {
    return alljoynJNI.AJ_GetVersion();
  }

  public static long AJ_GetElapsedTime(AJ_Time timer, int cumulative) {
    return alljoynJNI.AJ_GetElapsedTime(AJ_Time.getCPtr(timer), timer, cumulative);
  }

  public static AJ_Status _AJ_GetDebugTime(AJ_Time timer) {
    return AJ_Status.swigToEnum(alljoynJNI._AJ_GetDebugTime(AJ_Time.getCPtr(timer), timer));
  }

  public static void AJ_InitTimer(AJ_Time timer) {
    alljoynJNI.AJ_InitTimer(AJ_Time.getCPtr(timer), timer);
  }

  public static SWIGTYPE_p_int32_t AJ_GetTimeDifference(AJ_Time timerA, AJ_Time timerB) {
    return new SWIGTYPE_p_int32_t(alljoynJNI.AJ_GetTimeDifference(AJ_Time.getCPtr(timerA), timerA, AJ_Time.getCPtr(timerB), timerB), true);
  }

  public static void AJ_TimeAddOffset(AJ_Time timerA, long msec) {
    alljoynJNI.AJ_TimeAddOffset(AJ_Time.getCPtr(timerA), timerA, msec);
  }

  public static SWIGTYPE_p_int8_t AJ_CompareTime(AJ_Time timerA, AJ_Time timerB) {
    return new SWIGTYPE_p_int8_t(alljoynJNI.AJ_CompareTime(AJ_Time.getCPtr(timerA), timerA, AJ_Time.getCPtr(timerB), timerB), true);
  }

  public static void AJ_Sleep(long time) {
    alljoynJNI.AJ_Sleep(time);
  }

  public static SWIGTYPE_p_void AJ_Malloc(long size) {
    long cPtr = alljoynJNI.AJ_Malloc(size);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static SWIGTYPE_p_void AJ_Realloc(SWIGTYPE_p_void ptr, long size) {
    long cPtr = alljoynJNI.AJ_Realloc(SWIGTYPE_p_void.getCPtr(ptr), size);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static void AJ_Free(SWIGTYPE_p_void mem) {
    alljoynJNI.AJ_Free(SWIGTYPE_p_void.getCPtr(mem));
  }

  public static SWIGTYPE_p_int32_t AJ_StringFindFirstOf(String str, String chars) {
    return new SWIGTYPE_p_int32_t(alljoynJNI.AJ_StringFindFirstOf(str, chars), true);
  }

  public static AJ_Status AJ_RawToHex(SWIGTYPE_p_uint8_t raw, long rawLen, String hex, long hexLen, int lower) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_RawToHex(SWIGTYPE_p_uint8_t.getCPtr(raw), rawLen, hex, hexLen, lower));
  }

  public static AJ_Status AJ_HexToRaw(String hex, long hexLen, SWIGTYPE_p_uint8_t raw, long rawLen) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_HexToRaw(hex, hexLen, SWIGTYPE_p_uint8_t.getCPtr(raw), rawLen));
  }

  public static int AJ_StartReadFromStdIn() {
    return alljoynJNI.AJ_StartReadFromStdIn();
  }

  public static int AJ_StopReadFromStdIn() {
    return alljoynJNI.AJ_StopReadFromStdIn();
  }

  public static AJ_Status AJ_RawToB64(SWIGTYPE_p_uint8_t raw, long rawlen, String pem, long pemlen) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_RawToB64(SWIGTYPE_p_uint8_t.getCPtr(raw), rawlen, pem, pemlen));
  }

  public static AJ_Status AJ_B64ToRaw(String pem, long pemlen, SWIGTYPE_p_uint8_t raw, long rawlen) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_B64ToRaw(pem, pemlen, SWIGTYPE_p_uint8_t.getCPtr(raw), rawlen));
  }

  public static long AJ_ByteSwap16(long x) {
    return alljoynJNI.AJ_ByteSwap16(x);
  }

  public static long AJ_ByteSwap32(long x) {
    return alljoynJNI.AJ_ByteSwap32(x);
  }

  public static SWIGTYPE_p_uint64_t AJ_ByteSwap64(SWIGTYPE_p_uint64_t x) {
    return new SWIGTYPE_p_uint64_t(alljoynJNI.AJ_ByteSwap64(SWIGTYPE_p_uint64_t.getCPtr(x)), true);
  }

  public static AJ_Status AJ_IntToString(SWIGTYPE_p_int32_t val, String buf, long buflen) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_IntToString(SWIGTYPE_p_int32_t.getCPtr(val), buf, buflen));
  }

  public static AJ_Status AJ_InetToString(long addr, String buf, long buflen) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_InetToString(addr, buf, buflen));
  }

  public static String AJ_GetUniqueName(AJ_BusAttachment bus) {
    return alljoynJNI.AJ_GetUniqueName(AJ_BusAttachment.getCPtr(bus), bus);
  }

  public static AJ_Status AJ_BusRequestName(AJ_BusAttachment bus, String name, long flags) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_BusRequestName(AJ_BusAttachment.getCPtr(bus), bus, name, flags));
  }

  public static AJ_Status AJ_BusReleaseName(AJ_BusAttachment bus, String name) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_BusReleaseName(AJ_BusAttachment.getCPtr(bus), bus, name));
  }

  public static AJ_Status AJ_BusAdvertiseName(AJ_BusAttachment bus, String name, long transportMask, int op, int flags) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_BusAdvertiseName(AJ_BusAttachment.getCPtr(bus), bus, name, transportMask, op, flags));
  }

  public static AJ_Status AJ_BusFindAdvertisedName(AJ_BusAttachment bus, String namePrefix, int op) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_BusFindAdvertisedName(AJ_BusAttachment.getCPtr(bus), bus, namePrefix, op));
  }

  public static AJ_Status AJ_BusFindAdvertisedNameByTransport(AJ_BusAttachment bus, String namePrefix, long transport, int op) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_BusFindAdvertisedNameByTransport(AJ_BusAttachment.getCPtr(bus), bus, namePrefix, transport, op));
  }

  public static AJ_Status AJ_BusBindSessionPort(AJ_BusAttachment bus, long port, AJ_SessionOpts opts, int flags) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_BusBindSessionPort(AJ_BusAttachment.getCPtr(bus), bus, port, AJ_SessionOpts.getCPtr(opts), opts, flags));
  }

  public static AJ_Status AJ_BusUnbindSession(AJ_BusAttachment bus, long port) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_BusUnbindSession(AJ_BusAttachment.getCPtr(bus), bus, port));
  }

  public static AJ_Status AJ_BusCancelSessionless(AJ_BusAttachment bus, long serialNum) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_BusCancelSessionless(AJ_BusAttachment.getCPtr(bus), bus, serialNum));
  }

  public static AJ_Status AJ_BusReplyAcceptSession(_AJ_Message msg, long accept) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_BusReplyAcceptSession(_AJ_Message.getCPtr(msg), msg, accept));
  }

  public static AJ_Status AJ_BusJoinSession(AJ_BusAttachment bus, String sessionHost, long port, AJ_SessionOpts opts) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_BusJoinSession(AJ_BusAttachment.getCPtr(bus), bus, sessionHost, port, AJ_SessionOpts.getCPtr(opts), opts));
  }

  public static AJ_Status AJ_BusLeaveSession(AJ_BusAttachment bus, long sessionId) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_BusLeaveSession(AJ_BusAttachment.getCPtr(bus), bus, sessionId));
  }

  public static AJ_Status AJ_BusSetSignalRule(AJ_BusAttachment bus, String ruleString, int rule) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_BusSetSignalRule(AJ_BusAttachment.getCPtr(bus), bus, ruleString, rule));
  }

  public static AJ_Status AJ_BusSetSignalRuleSerial(AJ_BusAttachment bus, String ruleString, int rule, int flags, SWIGTYPE_p_uint32_t serialNum) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_BusSetSignalRuleSerial(AJ_BusAttachment.getCPtr(bus), bus, ruleString, rule, flags, SWIGTYPE_p_uint32_t.getCPtr(serialNum)));
  }

  public static AJ_Status AJ_BusAddSignalRule(AJ_BusAttachment bus, String signalName, String interfaceName, int rule) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_BusAddSignalRule(AJ_BusAttachment.getCPtr(bus), bus, signalName, interfaceName, rule));
  }

  public static AJ_Status AJ_BusSetSignalRuleFlags(AJ_BusAttachment bus, String ruleString, int rule, int flags) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_BusSetSignalRuleFlags(AJ_BusAttachment.getCPtr(bus), bus, ruleString, rule, flags));
  }

  public static AJ_Status AJ_BusSetLinkTimeout(AJ_BusAttachment bus, long sessionId, long linkTimeout) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_BusSetLinkTimeout(AJ_BusAttachment.getCPtr(bus), bus, sessionId, linkTimeout));
  }

  public static AJ_Status AJ_BusRemoveSessionMember(AJ_BusAttachment bus, long sessionId, String member) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_BusRemoveSessionMember(AJ_BusAttachment.getCPtr(bus), bus, sessionId, member));
  }

  public static AJ_Status AJ_BusPing(AJ_BusAttachment bus, String name, long timeout) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_BusPing(AJ_BusAttachment.getCPtr(bus), bus, name, timeout));
  }

  public static AJ_Status AJ_BusHandleBusMessage(_AJ_Message msg) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_BusHandleBusMessage(_AJ_Message.getCPtr(msg), msg));
  }

  public static void AJ_BusSetPasswordCallback(AJ_BusAttachment bus, SWIGTYPE_p_f_p_uint8_t_uint32_t__uint32_t pwdCallback) {
    alljoynJNI.AJ_BusSetPasswordCallback(AJ_BusAttachment.getCPtr(bus), bus, SWIGTYPE_p_f_p_uint8_t_uint32_t__uint32_t.getCPtr(pwdCallback));
  }

  public static void AJ_BusSetAuthListenerCallback(AJ_BusAttachment bus, SWIGTYPE_p_f_uint32_t_uint32_t_p_struct__AJ_Credential__AJ_Status authListenerCallback) {
    alljoynJNI.AJ_BusSetAuthListenerCallback(AJ_BusAttachment.getCPtr(bus), bus, SWIGTYPE_p_f_uint32_t_uint32_t_p_struct__AJ_Credential__AJ_Status.getCPtr(authListenerCallback));
  }

  public static AJ_Status AJ_BusAuthenticatePeer(AJ_BusAttachment bus, String peerBusName, SWIGTYPE_p_f_p_q_const__void_enum_AJ_Status__void callback, SWIGTYPE_p_void cbContext) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_BusAuthenticatePeer(AJ_BusAttachment.getCPtr(bus), bus, peerBusName, SWIGTYPE_p_f_p_q_const__void_enum_AJ_Status__void.getCPtr(callback), SWIGTYPE_p_void.getCPtr(cbContext)));
  }

  public static AJ_Status AJ_BusPropGet(_AJ_Message msg, SWIGTYPE_p_f_p_struct__AJ_Message_uint32_t_p_void__AJ_Status callback, SWIGTYPE_p_void context) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_BusPropGet(_AJ_Message.getCPtr(msg), msg, SWIGTYPE_p_f_p_struct__AJ_Message_uint32_t_p_void__AJ_Status.getCPtr(callback), SWIGTYPE_p_void.getCPtr(context)));
  }

  public static AJ_Status AJ_BusPropGetAll(_AJ_Message msg, SWIGTYPE_p_f_p_struct__AJ_Message_uint32_t_p_void__AJ_Status callback, SWIGTYPE_p_void context) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_BusPropGetAll(_AJ_Message.getCPtr(msg), msg, SWIGTYPE_p_f_p_struct__AJ_Message_uint32_t_p_void__AJ_Status.getCPtr(callback), SWIGTYPE_p_void.getCPtr(context)));
  }

  public static AJ_Status AJ_BusPropSet(_AJ_Message msg, SWIGTYPE_p_f_p_struct__AJ_Message_uint32_t_p_void__AJ_Status callback, SWIGTYPE_p_void context) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_BusPropSet(_AJ_Message.getCPtr(msg), msg, SWIGTYPE_p_f_p_struct__AJ_Message_uint32_t_p_void__AJ_Status.getCPtr(callback), SWIGTYPE_p_void.getCPtr(context)));
  }

  public static AJ_Status AJ_BusEnableSecurity(AJ_BusAttachment bus, SWIGTYPE_p_uint32_t suites, long numsuites) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_BusEnableSecurity(AJ_BusAttachment.getCPtr(bus), bus, SWIGTYPE_p_uint32_t.getCPtr(suites), numsuites));
  }

  public static AJ_Status AJ_UnmarshalMsg(AJ_BusAttachment bus, _AJ_Message msg, long timeout) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_UnmarshalMsg(AJ_BusAttachment.getCPtr(bus), bus, _AJ_Message.getCPtr(msg), msg, timeout));
  }

  public static AJ_Status AJ_UnmarshalArg(_AJ_Message msg, _AJ_Arg arg) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_UnmarshalArg(_AJ_Message.getCPtr(msg), msg, _AJ_Arg.getCPtr(arg), arg));
  }

  public static AJ_Status AJ_SkipArg(_AJ_Message msg) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_SkipArg(_AJ_Message.getCPtr(msg), msg));
  }

  public static AJ_Status AJ_ResetArgs(_AJ_Message msg) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_ResetArgs(_AJ_Message.getCPtr(msg), msg));
  }

  public static AJ_Status AJ_UnmarshalArgs(_AJ_Message msg, String signature) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_UnmarshalArgs(_AJ_Message.getCPtr(msg), msg, signature));
  }

  public static AJ_Status AJ_UnmarshalRaw(_AJ_Message msg, SWIGTYPE_p_p_void data, long len, SWIGTYPE_p_size_t actual) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_UnmarshalRaw(_AJ_Message.getCPtr(msg), msg, SWIGTYPE_p_p_void.getCPtr(data), len, SWIGTYPE_p_size_t.getCPtr(actual)));
  }

  public static AJ_Status AJ_UnmarshalContainer(_AJ_Message msg, _AJ_Arg arg, int typeId) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_UnmarshalContainer(_AJ_Message.getCPtr(msg), msg, _AJ_Arg.getCPtr(arg), arg, typeId));
  }

  public static AJ_Status AJ_UnmarshalCloseContainer(_AJ_Message msg, _AJ_Arg arg) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_UnmarshalCloseContainer(_AJ_Message.getCPtr(msg), msg, _AJ_Arg.getCPtr(arg), arg));
  }

  public static AJ_Status AJ_UnmarshalVariant(_AJ_Message msg, SWIGTYPE_p_p_char sig) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_UnmarshalVariant(_AJ_Message.getCPtr(msg), msg, SWIGTYPE_p_p_char.getCPtr(sig)));
  }

  public static AJ_Status AJ_CloseMsg(_AJ_Message msg) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_CloseMsg(_AJ_Message.getCPtr(msg), msg));
  }

  public static AJ_Status AJ_MarshalMethodCall(AJ_BusAttachment bus, _AJ_Message msg, long msgId, String destination, long sessionId, int flags, long timeout) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_MarshalMethodCall(AJ_BusAttachment.getCPtr(bus), bus, _AJ_Message.getCPtr(msg), msg, msgId, destination, sessionId, flags, timeout));
  }

  public static AJ_Status AJ_MarshalSignal(AJ_BusAttachment bus, _AJ_Message msg, long msgId, String destination, long sessionId, int flags, long ttl) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_MarshalSignal(AJ_BusAttachment.getCPtr(bus), bus, _AJ_Message.getCPtr(msg), msg, msgId, destination, sessionId, flags, ttl));
  }

  public static AJ_Status AJ_MarshalReplyMsg(_AJ_Message methodCall, _AJ_Message reply) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_MarshalReplyMsg(_AJ_Message.getCPtr(methodCall), methodCall, _AJ_Message.getCPtr(reply), reply));
  }

  public static AJ_Status AJ_MarshalErrorMsg(_AJ_Message methodCall, _AJ_Message reply, String error) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_MarshalErrorMsg(_AJ_Message.getCPtr(methodCall), methodCall, _AJ_Message.getCPtr(reply), reply, error));
  }

  public static AJ_Status AJ_MarshalStatusMsg(_AJ_Message methodCall, _AJ_Message reply, AJ_Status status) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_MarshalStatusMsg(_AJ_Message.getCPtr(methodCall), methodCall, _AJ_Message.getCPtr(reply), reply, status.swigValue()));
  }

  public static AJ_Status AJ_DeliverMsg(_AJ_Message msg) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_DeliverMsg(_AJ_Message.getCPtr(msg), msg));
  }

  public static AJ_Status AJ_DeliverMsgPartial(_AJ_Message msg, long bytesRemaining) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_DeliverMsgPartial(_AJ_Message.getCPtr(msg), msg, bytesRemaining));
  }

  public static AJ_Status AJ_MarshalArgs(_AJ_Message msg, String signature) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_MarshalArgs(_AJ_Message.getCPtr(msg), msg, signature));
  }

  public static _AJ_Arg AJ_InitArg(_AJ_Arg arg, int typeId, int flags, SWIGTYPE_p_void val, long len) {
    long cPtr = alljoynJNI.AJ_InitArg(_AJ_Arg.getCPtr(arg), arg, typeId, flags, SWIGTYPE_p_void.getCPtr(val), len);
    return (cPtr == 0) ? null : new _AJ_Arg(cPtr, false);
  }

  public static AJ_Status AJ_MarshalArg(_AJ_Message msg, _AJ_Arg arg) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_MarshalArg(_AJ_Message.getCPtr(msg), msg, _AJ_Arg.getCPtr(arg), arg));
  }

  public static AJ_Status AJ_MarshalRaw(_AJ_Message msg, SWIGTYPE_p_void data, long len) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_MarshalRaw(_AJ_Message.getCPtr(msg), msg, SWIGTYPE_p_void.getCPtr(data), len));
  }

  public static AJ_Status AJ_MarshalContainer(_AJ_Message msg, _AJ_Arg arg, int typeId) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_MarshalContainer(_AJ_Message.getCPtr(msg), msg, _AJ_Arg.getCPtr(arg), arg, typeId));
  }

  public static AJ_Status AJ_MarshalCloseContainer(_AJ_Message msg, _AJ_Arg arg) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_MarshalCloseContainer(_AJ_Message.getCPtr(msg), msg, _AJ_Arg.getCPtr(arg), arg));
  }

  public static AJ_Status AJ_MarshalVariant(_AJ_Message msg, String sig) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_MarshalVariant(_AJ_Message.getCPtr(msg), msg, sig));
  }

  public static void _AJ_DumpMsg(String tag, _AJ_Message msg, int body) {
    alljoynJNI._AJ_DumpMsg(tag, _AJ_Message.getCPtr(msg), msg, body);
  }

  public static void _AJ_DumpBytes(String tag, SWIGTYPE_p_uint8_t data, long len) {
    alljoynJNI._AJ_DumpBytes(tag, SWIGTYPE_p_uint8_t.getCPtr(data), len);
  }

  public static int _AJ_DbgEnabled(String module) {
    return alljoynJNI._AJ_DbgEnabled(module);
  }

  public static int _AJ_DbgHeader(long level, String file, int line) {
    return alljoynJNI._AJ_DbgHeader(level, file, line);
  }

  public static String AJ_StatusText(AJ_Status status) {
    return alljoynJNI.AJ_StatusText(status.swigValue());
  }

  public static void AJ_Initialize() {
    alljoynJNI.AJ_Initialize();
  }

  public static long AJ_DESCRIPTION_ID(long arg0, long arg1, long arg2, long arg3) {
    return alljoynJNI.AJ_DESCRIPTION_ID(arg0, arg1, arg2, arg3);
  }

  public static long AJ_DESC_ID_FROM_MSG_ID(long arg0, long arg1) {
    return alljoynJNI.AJ_DESC_ID_FROM_MSG_ID(arg0, arg1);
  }

  public static long AJ_DESC_ID_FROM_PROP_ID(long arg0) {
    return alljoynJNI.AJ_DESC_ID_FROM_PROP_ID(arg0);
  }

  public static long AJ_DESC_ID_FROM_OBJ_INDEX(long arg0) {
    return alljoynJNI.AJ_DESC_ID_FROM_OBJ_INDEX(arg0);
  }

  public static long AJ_DESC_ID_FROM_INTERFACE_INDEX(long arg0, long arg1) {
    return alljoynJNI.AJ_DESC_ID_FROM_INTERFACE_INDEX(arg0, arg1);
  }

  public static long AJ_BUS_MESSAGE_ID(long arg0, long arg1, long arg2) {
    return alljoynJNI.AJ_BUS_MESSAGE_ID(arg0, arg1, arg2);
  }

  public static long AJ_APP_MESSAGE_ID(long arg0, long arg1, long arg2) {
    return alljoynJNI.AJ_APP_MESSAGE_ID(arg0, arg1, arg2);
  }

  public static long AJ_PRX_MESSAGE_ID(long arg0, long arg1, long arg2) {
    return alljoynJNI.AJ_PRX_MESSAGE_ID(arg0, arg1, arg2);
  }

  public static long AJ_BUS_PROPERTY_ID(long arg0, long arg1, long arg2) {
    return alljoynJNI.AJ_BUS_PROPERTY_ID(arg0, arg1, arg2);
  }

  public static long AJ_APP_PROPERTY_ID(long arg0, long arg1, long arg2) {
    return alljoynJNI.AJ_APP_PROPERTY_ID(arg0, arg1, arg2);
  }

  public static long AJ_PRX_PROPERTY_ID(long arg0, long arg1, long arg2) {
    return alljoynJNI.AJ_PRX_PROPERTY_ID(arg0, arg1, arg2);
  }

  public static long AJ_REPLY_ID(long arg0) {
    return alljoynJNI.AJ_REPLY_ID(arg0);
  }

  public static AJ_Object getAJ_ROOT_OBJECT() {
    long cPtr = alljoynJNI.AJ_ROOT_OBJECT_get();
    return (cPtr == 0) ? null : new AJ_Object(cPtr, false);
  }

  public static AJ_Status AJ_RegisterObjectList(AJ_Object objList, int index) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_RegisterObjectList(AJ_Object.getCPtr(objList), objList, index));
  }

  public static AJ_Status AJ_RegisterObjectListWithDescriptions(AJ_Object objList, int index, SWIGTYPE_p_f_uint32_t_p_q_const__char__p_char descLookup) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_RegisterObjectListWithDescriptions(AJ_Object.getCPtr(objList), objList, index, SWIGTYPE_p_f_uint32_t_p_q_const__char__p_char.getCPtr(descLookup)));
  }

  public static void AJ_RegisterDescriptionLanguages(SWIGTYPE_p_p_char languages) {
    alljoynJNI.AJ_RegisterDescriptionLanguages(SWIGTYPE_p_p_char.getCPtr(languages));
  }

  public static void AJ_RegisterObjects(AJ_Object localObjects, AJ_Object proxyObjects) {
    alljoynJNI.AJ_RegisterObjects(AJ_Object.getCPtr(localObjects), localObjects, AJ_Object.getCPtr(proxyObjects), proxyObjects);
  }

  public static AJ_Object AJ_InitObjectIterator(AJ_ObjectIterator iter, int inFlags, int exFlags) {
    long cPtr = alljoynJNI.AJ_InitObjectIterator(AJ_ObjectIterator.getCPtr(iter), iter, inFlags, exFlags);
    return (cPtr == 0) ? null : new AJ_Object(cPtr, false);
  }

  public static AJ_Object AJ_NextObject(AJ_ObjectIterator iter) {
    long cPtr = alljoynJNI.AJ_NextObject(AJ_ObjectIterator.getCPtr(iter), iter);
    return (cPtr == 0) ? null : new AJ_Object(cPtr, false);
  }

  public static SWIGTYPE_p_p_p_char AJ_InterfacesCreate() {
    long cPtr = alljoynJNI.AJ_InterfacesCreate();
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_p_char(cPtr, false);
  }

  public static SWIGTYPE_p_p_p_char AJ_InterfacesAdd(SWIGTYPE_p_p_p_char arg0, SWIGTYPE_p_p_char arg1) {
    long cPtr = alljoynJNI.AJ_InterfacesAdd(SWIGTYPE_p_p_p_char.getCPtr(arg0), SWIGTYPE_p_p_char.getCPtr(arg1));
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_p_char(cPtr, false);
  }

  public static AJ_Status AJ_InterfacesDelete(SWIGTYPE_p_p_p_char arg0) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_InterfacesDelete(SWIGTYPE_p_p_p_char.getCPtr(arg0)));
  }

  public static SWIGTYPE_p_p_char AJ_InterfaceDescriptionCreate(String arg0) {
    long cPtr = alljoynJNI.AJ_InterfaceDescriptionCreate(arg0);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_char(cPtr, false);
  }

  public static SWIGTYPE_p_p_char AJ_InterfaceDescriptionAdd(SWIGTYPE_p_p_char arg0, String arg1) {
    long cPtr = alljoynJNI.AJ_InterfaceDescriptionAdd(SWIGTYPE_p_p_char.getCPtr(arg0), arg1);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_char(cPtr, false);
  }

  public static AJ_Status AJ_InterfaceDescriptionDelete(SWIGTYPE_p_p_char arg0) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_InterfaceDescriptionDelete(SWIGTYPE_p_p_char.getCPtr(arg0)));
  }

  public static AJ_Object AJ_ObjectsCreate() {
    long cPtr = alljoynJNI.AJ_ObjectsCreate();
    return (cPtr == 0) ? null : new AJ_Object(cPtr, false);
  }

  public static AJ_Object AJ_ObjectsAdd(AJ_Object arg0, AJ_Object arg1) {
    long cPtr = alljoynJNI.AJ_ObjectsAdd(AJ_Object.getCPtr(arg0), arg0, AJ_Object.getCPtr(arg1), arg1);
    return (cPtr == 0) ? null : new AJ_Object(cPtr, false);
  }

  public static AJ_Status AJ_IdentifyMessage(_AJ_Message msg) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_IdentifyMessage(_AJ_Message.getCPtr(msg), msg));
  }

  public static AJ_Status AJ_UnmarshalPropertyArgs(_AJ_Message msg, SWIGTYPE_p_uint32_t propId, SWIGTYPE_p_p_char sig) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_UnmarshalPropertyArgs(_AJ_Message.getCPtr(msg), msg, SWIGTYPE_p_uint32_t.getCPtr(propId), SWIGTYPE_p_p_char.getCPtr(sig)));
  }

  public static AJ_Status AJ_MarshalPropertyArgs(_AJ_Message msg, long propId) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_MarshalPropertyArgs(_AJ_Message.getCPtr(msg), msg, propId));
  }

  public static AJ_Status AJ_MarshalAllPropertiesArgs(_AJ_Message replyMsg, String iface, SWIGTYPE_p_f_p_struct__AJ_Message_uint32_t_p_void__AJ_Status callback, SWIGTYPE_p_void context) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_MarshalAllPropertiesArgs(_AJ_Message.getCPtr(replyMsg), replyMsg, iface, SWIGTYPE_p_f_p_struct__AJ_Message_uint32_t_p_void__AJ_Status.getCPtr(callback), SWIGTYPE_p_void.getCPtr(context)));
  }

  public static AJ_Status AJ_HandleIntrospectRequest(_AJ_Message msg, _AJ_Message reply, String languageTag) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_HandleIntrospectRequest(_AJ_Message.getCPtr(msg), msg, _AJ_Message.getCPtr(reply), reply, languageTag));
  }

  public static AJ_Status AJ_HandleGetDescriptionLanguages(_AJ_Message msg, _AJ_Message reply) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_HandleGetDescriptionLanguages(_AJ_Message.getCPtr(msg), msg, _AJ_Message.getCPtr(reply), reply));
  }

  public static AJ_Status AJ_InitMessageFromMsgId(_AJ_Message msg, long msgId, int msgType, SWIGTYPE_p_uint8_t secure) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_InitMessageFromMsgId(_AJ_Message.getCPtr(msg), msg, msgId, msgType, SWIGTYPE_p_uint8_t.getCPtr(secure)));
  }

  public static AJ_Status AJ_SetProxyObjectPath(AJ_Object proxyObjects, long msgId, String objPath) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_SetProxyObjectPath(AJ_Object.getCPtr(proxyObjects), proxyObjects, msgId, objPath));
  }

  public static AJ_Status AJ_AllocReplyContext(_AJ_Message msg, long timeout) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_AllocReplyContext(_AJ_Message.getCPtr(msg), msg, timeout));
  }

  public static void AJ_ReleaseReplyContexts() {
    alljoynJNI.AJ_ReleaseReplyContexts();
  }

  public static int AJ_TimedOutMethodCall(_AJ_Message msg) {
    return alljoynJNI.AJ_TimedOutMethodCall(_AJ_Message.getCPtr(msg), msg);
  }

  public static void AJ_ReleaseReplyContext(_AJ_Message msg) {
    alljoynJNI.AJ_ReleaseReplyContext(_AJ_Message.getCPtr(msg), msg);
  }

  public static AJ_Status AJ_SetObjectFlags(String objPath, int setFlags, int clearFlags) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_SetObjectFlags(objPath, setFlags, clearFlags));
  }

  public static AJ_MemberType AJ_GetMemberType(long identifier, SWIGTYPE_p_p_char member, SWIGTYPE_p_uint8_t isSecure) {
    return AJ_MemberType.swigToEnum(alljoynJNI.AJ_GetMemberType(identifier, SWIGTYPE_p_p_char.getCPtr(member), SWIGTYPE_p_uint8_t.getCPtr(isSecure)));
  }

  public static void AJ_PrintXML(AJ_Object objs) {
    alljoynJNI.AJ_PrintXML(AJ_Object.getCPtr(objs), objs);
  }

  public static void AJ_PrintXMLWithDescriptions(AJ_Object objs, String languageTag) {
    alljoynJNI.AJ_PrintXMLWithDescriptions(AJ_Object.getCPtr(objs), objs, languageTag);
  }

  public static String getAJ_DBusDestination() {
    return alljoynJNI.AJ_DBusDestination_get();
  }

  public static String getAJ_BusDestination() {
    return alljoynJNI.AJ_BusDestination_get();
  }

  public static String getAJ_ErrSecurityViolation() {
    return alljoynJNI.AJ_ErrSecurityViolation_get();
  }

  public static String getAJ_ErrTimeout() {
    return alljoynJNI.AJ_ErrTimeout_get();
  }

  public static String getAJ_ErrRejected() {
    return alljoynJNI.AJ_ErrRejected_get();
  }

  public static String getAJ_ErrResources() {
    return alljoynJNI.AJ_ErrResources_get();
  }

  public static String getAJ_ErrServiceUnknown() {
    return alljoynJNI.AJ_ErrServiceUnknown_get();
  }

  public static String getAJ_ErrUpdateNotAllowed() {
    return alljoynJNI.AJ_ErrUpdateNotAllowed_get();
  }

  public static String getAJ_ErrInvalidValue() {
    return alljoynJNI.AJ_ErrInvalidValue_get();
  }

  public static String getAJ_ErrFeatureNotAvailable() {
    return alljoynJNI.AJ_ErrFeatureNotAvailable_get();
  }

  public static String getAJ_ErrMaxSizeExceeded() {
    return alljoynJNI.AJ_ErrMaxSizeExceeded_get();
  }

  public static String getAJ_ErrLanguageNotSuppored() {
    return alljoynJNI.AJ_ErrLanguageNotSuppored_get();
  }

  public static SWIGTYPE_p_p_char getAJ_PropertiesIface() {
    long cPtr = alljoynJNI.AJ_PropertiesIface_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_char(cPtr, false);
  }

  public static String getDBusPeerInterface() {
    return alljoynJNI.DBusPeerInterface_get();
  }

  public static SWIGTYPE_p_p_char getAJ_IntrospectionIface() {
    long cPtr = alljoynJNI.AJ_IntrospectionIface_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_char(cPtr, false);
  }

  public static String getAllSeenIntrospectableInterface() {
    return alljoynJNI.AllSeenIntrospectableInterface_get();
  }

  public static SWIGTYPE_p_p_char getAJ_AllSeenIntrospectionIface() {
    long cPtr = alljoynJNI.AJ_AllSeenIntrospectionIface_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_char(cPtr, false);
  }

  public static AJ_Object getAJ_StandardObjects() {
    long cPtr = alljoynJNI.AJ_StandardObjects_get();
    return (cPtr == 0) ? null : new AJ_Object(cPtr, false);
  }

  public static void AJ_SetMinProtoVersion(int min) {
    alljoynJNI.AJ_SetMinProtoVersion(min);
  }

  public static int AJ_GetMinProtoVersion() {
    return alljoynJNI.AJ_GetMinProtoVersion();
  }

  public static int AJ_GetRoutingProtoVersion() {
    return alljoynJNI.AJ_GetRoutingProtoVersion();
  }

  public static AJ_Status AJ_Authenticate(AJ_BusAttachment bus) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_Authenticate(AJ_BusAttachment.getCPtr(bus), bus));
  }

  public static AJ_Status AJ_Connect(AJ_BusAttachment bus, String serviceName, long timeout) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_Connect(AJ_BusAttachment.getCPtr(bus), bus, serviceName, timeout));
  }

  public static AJ_Status AJ_FindBusAndConnect(AJ_BusAttachment bus, String serviceName, long timeout) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_FindBusAndConnect(AJ_BusAttachment.getCPtr(bus), bus, serviceName, timeout));
  }

  public static void AJ_Disconnect(AJ_BusAttachment bus) {
    alljoynJNI.AJ_Disconnect(AJ_BusAttachment.getCPtr(bus), bus);
  }

  public static void SetBusAuthPwdCallback(SWIGTYPE_p_f_p_uint8_t_uint32_t__uint32_t callback) {
    alljoynJNI.SetBusAuthPwdCallback(SWIGTYPE_p_f_p_uint8_t_uint32_t__uint32_t.getCPtr(callback));
  }

  public static int AJ_IsRoutingNodeBlacklisted(SWIGTYPE_p_AJ_Service service) {
    return alljoynJNI.AJ_IsRoutingNodeBlacklisted(SWIGTYPE_p_AJ_Service.getCPtr(service));
  }

  public static void AJ_InitRoutingNodeBlacklist() {
    alljoynJNI.AJ_InitRoutingNodeBlacklist();
  }

  public static void AJ_AboutRegisterPropStoreGetter(SWIGTYPE_p_f_p_struct__AJ_Message_p_q_const__char__AJ_Status propGetter) {
    alljoynJNI.AJ_AboutRegisterPropStoreGetter(SWIGTYPE_p_f_p_struct__AJ_Message_p_q_const__char__AJ_Status.getCPtr(propGetter));
  }

  public static AJ_Status AJ_AboutInit(AJ_BusAttachment bus, long boundPort) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_AboutInit(AJ_BusAttachment.getCPtr(bus), bus, boundPort));
  }

  public static AJ_Status AJ_AboutAnnounce(AJ_BusAttachment bus) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_AboutAnnounce(AJ_BusAttachment.getCPtr(bus), bus));
  }

  public static void AJ_AboutSetIcon(SWIGTYPE_p_uint8_t icon, long size, String mimeType, String url) {
    alljoynJNI.AJ_AboutSetIcon(SWIGTYPE_p_uint8_t.getCPtr(icon), size, mimeType, url);
  }

  public static AJ_Status AJ_AboutHandleGetProp(_AJ_Message msg) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_AboutHandleGetProp(_AJ_Message.getCPtr(msg), msg));
  }

  public static AJ_Status AJ_AboutHandleGetAboutData(_AJ_Message msg, _AJ_Message reply) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_AboutHandleGetAboutData(_AJ_Message.getCPtr(msg), msg, _AJ_Message.getCPtr(reply), reply));
  }

  public static AJ_Status AJ_AboutHandleGetObjectDescription(_AJ_Message msg, _AJ_Message reply) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_AboutHandleGetObjectDescription(_AJ_Message.getCPtr(msg), msg, _AJ_Message.getCPtr(reply), reply));
  }

  public static AJ_Status AJ_AboutIconHandleGetProp(_AJ_Message msg) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_AboutIconHandleGetProp(_AJ_Message.getCPtr(msg), msg));
  }

  public static AJ_Status AJ_AboutIconHandleGetURL(_AJ_Message msg, _AJ_Message reply) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_AboutIconHandleGetURL(_AJ_Message.getCPtr(msg), msg, _AJ_Message.getCPtr(reply), reply));
  }

  public static AJ_Status AJ_AboutIconHandleGetContent(_AJ_Message msg, _AJ_Message reply) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_AboutIconHandleGetContent(_AJ_Message.getCPtr(msg), msg, _AJ_Message.getCPtr(reply), reply));
  }

  public static void AJ_AboutSetShouldAnnounce() {
    alljoynJNI.AJ_AboutSetShouldAnnounce();
  }

  public static void AJ_AboutSetAnnounceObjects(AJ_Object objList) {
    alljoynJNI.AJ_AboutSetAnnounceObjects(AJ_Object.getCPtr(objList), objList);
  }

  public static AJ_Status AJ_RunAllJoynService(AJ_BusAttachment bus, AllJoynConfiguration config) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_RunAllJoynService(AJ_BusAttachment.getCPtr(bus), bus, AllJoynConfiguration.getCPtr(config), config));
  }

  public static long AJ_SetTimer(long relative_time, SWIGTYPE_p_f_p_void__void handler, SWIGTYPE_p_void context, long repeat) {
    return alljoynJNI.AJ_SetTimer(relative_time, SWIGTYPE_p_f_p_void__void.getCPtr(handler), SWIGTYPE_p_void.getCPtr(context), repeat);
  }

  public static void AJ_CancelTimer(long id) {
    alljoynJNI.AJ_CancelTimer(id);
  }

  public static AJ_Status AJ_StartService(AJ_BusAttachment bus, String daemonName, long timeout, int connected, long port, String name, long flags, AJ_SessionOpts opts) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_StartService(AJ_BusAttachment.getCPtr(bus), bus, daemonName, timeout, connected, port, name, flags, AJ_SessionOpts.getCPtr(opts), opts));
  }

  public static AJ_Status AJ_StartClient(AJ_BusAttachment bus, String daemonName, long timeout, int connected, String name, long port, int[] sessionId, AJ_SessionOpts opts) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_StartClient(AJ_BusAttachment.getCPtr(bus), bus, daemonName, timeout, connected, name, port, sessionId, AJ_SessionOpts.getCPtr(opts), opts));
  }

  public static AJ_Status AJ_StartClientByName(AJ_BusAttachment bus, String daemonName, long timeout, int connected, String name, long port, int[] sessionId, AJ_SessionOpts opts, String fullName) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_StartClientByName(AJ_BusAttachment.getCPtr(bus), bus, daemonName, timeout, connected, name, port, sessionId, AJ_SessionOpts.getCPtr(opts), opts, fullName));
  }

  public static AJ_Status AJ_StartClientByInterface(AJ_BusAttachment bus, String daemonName, long timeout, int connected, SWIGTYPE_p_p_char interfaces, int[] sessionId, String uniqueName, AJ_SessionOpts opts) {
    return AJ_Status.swigToEnum(alljoynJNI.AJ_StartClientByInterface(AJ_BusAttachment.getCPtr(bus), bus, daemonName, timeout, connected, SWIGTYPE_p_p_char.getCPtr(interfaces), sessionId, uniqueName, AJ_SessionOpts.getCPtr(opts), opts));
  }

}
