/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package alljoyn;

public class AllJoynConfiguration {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected AllJoynConfiguration(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AllJoynConfiguration obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        alljoynJNI.delete_AllJoynConfiguration(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDaemonName(String value) {
    alljoynJNI.AllJoynConfiguration_daemonName_set(swigCPtr, this, value);
  }

  public String getDaemonName() {
    return alljoynJNI.AllJoynConfiguration_daemonName_get(swigCPtr, this);
  }

  public void setConnect_timeout(long value) {
    alljoynJNI.AllJoynConfiguration_connect_timeout_set(swigCPtr, this, value);
  }

  public long getConnect_timeout() {
    return alljoynJNI.AllJoynConfiguration_connect_timeout_get(swigCPtr, this);
  }

  public void setConnected(int value) {
    alljoynJNI.AllJoynConfiguration_connected_set(swigCPtr, this, value);
  }

  public int getConnected() {
    return alljoynJNI.AllJoynConfiguration_connected_get(swigCPtr, this);
  }

  public void setSession_port(long value) {
    alljoynJNI.AllJoynConfiguration_session_port_set(swigCPtr, this, value);
  }

  public long getSession_port() {
    return alljoynJNI.AllJoynConfiguration_session_port_get(swigCPtr, this);
  }

  public void setService_name(String value) {
    alljoynJNI.AllJoynConfiguration_service_name_set(swigCPtr, this, value);
  }

  public String getService_name() {
    return alljoynJNI.AllJoynConfiguration_service_name_get(swigCPtr, this);
  }

  public void setFlags(long value) {
    alljoynJNI.AllJoynConfiguration_flags_set(swigCPtr, this, value);
  }

  public long getFlags() {
    return alljoynJNI.AllJoynConfiguration_flags_get(swigCPtr, this);
  }

  public void setOpts(AJ_SessionOpts value) {
    alljoynJNI.AllJoynConfiguration_opts_set(swigCPtr, this, AJ_SessionOpts.getCPtr(value), value);
  }

  public AJ_SessionOpts getOpts() {
    long cPtr = alljoynJNI.AllJoynConfiguration_opts_get(swigCPtr, this);
    return (cPtr == 0) ? null : new AJ_SessionOpts(cPtr, false);
  }

  public void setPassword_callback(SWIGTYPE_p_f_p_uint8_t_uint32_t__uint32_t value) {
    alljoynJNI.AllJoynConfiguration_password_callback_set(swigCPtr, this, SWIGTYPE_p_f_p_uint8_t_uint32_t__uint32_t.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_uint8_t_uint32_t__uint32_t getPassword_callback() {
    long cPtr = alljoynJNI.AllJoynConfiguration_password_callback_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_uint8_t_uint32_t__uint32_t(cPtr, false);
  }

  public void setLink_timeout(long value) {
    alljoynJNI.AllJoynConfiguration_link_timeout_set(swigCPtr, this, value);
  }

  public long getLink_timeout() {
    return alljoynJNI.AllJoynConfiguration_link_timeout_get(swigCPtr, this);
  }

  public void setAcceptor(SWIGTYPE_p_f_p_struct__AJ_Message__uint8_t value) {
    alljoynJNI.AllJoynConfiguration_acceptor_set(swigCPtr, this, SWIGTYPE_p_f_p_struct__AJ_Message__uint8_t.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct__AJ_Message__uint8_t getAcceptor() {
    long cPtr = alljoynJNI.AllJoynConfiguration_acceptor_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct__AJ_Message__uint8_t(cPtr, false);
  }

  public void setConnection_handler(SWIGTYPE_p_f_uint8_t__void value) {
    alljoynJNI.AllJoynConfiguration_connection_handler_set(swigCPtr, this, SWIGTYPE_p_f_uint8_t__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_uint8_t__void getConnection_handler() {
    long cPtr = alljoynJNI.AllJoynConfiguration_connection_handler_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_uint8_t__void(cPtr, false);
  }

  public void setMessage_handlers(MessageHandlerEntry value) {
    alljoynJNI.AllJoynConfiguration_message_handlers_set(swigCPtr, this, MessageHandlerEntry.getCPtr(value), value);
  }

  public MessageHandlerEntry getMessage_handlers() {
    long cPtr = alljoynJNI.AllJoynConfiguration_message_handlers_get(swigCPtr, this);
    return (cPtr == 0) ? null : new MessageHandlerEntry(cPtr, false);
  }

  public void setProp_handlers(PropHandlerEntry value) {
    alljoynJNI.AllJoynConfiguration_prop_handlers_set(swigCPtr, this, PropHandlerEntry.getCPtr(value), value);
  }

  public PropHandlerEntry getProp_handlers() {
    long cPtr = alljoynJNI.AllJoynConfiguration_prop_handlers_get(swigCPtr, this);
    return (cPtr == 0) ? null : new PropHandlerEntry(cPtr, false);
  }

  public AllJoynConfiguration() {
    this(alljoynJNI.new_AllJoynConfiguration(), true);
  }

}
