/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package alljoyn;

public class MessageHandlerEntry {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MessageHandlerEntry(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MessageHandlerEntry obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        alljoynJNI.delete_MessageHandlerEntry(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMsgid(long value) {
    alljoynJNI.MessageHandlerEntry_msgid_set(swigCPtr, this, value);
  }

  public long getMsgid() {
    return alljoynJNI.MessageHandlerEntry_msgid_get(swigCPtr, this);
  }

  public void setHandler(SWIGTYPE_p_f_p_struct__AJ_Message_p_struct__AJ_Message__AJ_Status value) {
    alljoynJNI.MessageHandlerEntry_handler_set(swigCPtr, this, SWIGTYPE_p_f_p_struct__AJ_Message_p_struct__AJ_Message__AJ_Status.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct__AJ_Message_p_struct__AJ_Message__AJ_Status getHandler() {
    long cPtr = alljoynJNI.MessageHandlerEntry_handler_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct__AJ_Message_p_struct__AJ_Message__AJ_Status(cPtr, false);
  }

  public MessageHandlerEntry() {
    this(alljoynJNI.new_MessageHandlerEntry(), true);
  }

}
