/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package alljoyn;

public class SWIGTYPE_p_f_p_struct__AJ_IOBuffer__AJ_Status {
  private long swigCPtr;

  protected SWIGTYPE_p_f_p_struct__AJ_IOBuffer__AJ_Status(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_f_p_struct__AJ_IOBuffer__AJ_Status() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_f_p_struct__AJ_IOBuffer__AJ_Status obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

